### ISSUE TITLE
Depend on python-lsp-server-base instead of python-lsp-server, as it differs from pypi

### ISSUE THREAD

**Issue by jonas-w** [conda-forge/python-lsp-ruff-feedstock#3]
### Comment:

The conda-forge package "python-lsp-server" is equivalent to "python-lsp-server[all]" on PyPI. Which installs dependencies like pylint, pydocstyle, etc.. which all can be replaced by ruff.

The PyPI package "python-lsp-ruff" only dependends on the "python-lsp-server" PyPI package which would be "python-lsp-server-base" on conda-forge. 

The conda-forge package "python-lsp-server" depends on "python-lsp-server-base", so it shouldn't break existing installations and if people want the current behaviour they simply can install the "python-lsp-server" conda-forge package and there will be no dependency problems.

Would be great if this could be changed, as this differs from the pypi package.

Thanks!

**Comment by bollwyvl** [comment]
This seems very reasonable, and should be a one line PR, if you'd like to do so, and even nominate yourself as a co-maintainer. Otherwise, we can take a look at it at some point...
